#client:
#  account-uri: ENC(9jm6QhmP5N1qIFjGPAVC4JDxSa+eITt8dWKZdNkMu3e8+TxcEhdZX0wxUyveL5SgbwI4av1nHq0amGMne+1aAGC0Qlro1vi+Zw4TuPhr/DmHV9qCFapCO6VQsShMmufr)
#  batch-uri: ENC(iYEHMpxbfvZEnLu0gjVkHwz+Yj3haowsBMk17jmN++tle+4/PW+3CrWkdGM+4m3+sUbDN1drEyO7H9eBASh8/Hqq+Tm1JfhaMTl/GC1AmtWQHA+Jh2ehaKuA70RFLzIL)
#  maker-user: ENC(dYAgRW340dYheD5ZAmwT3zfgh7Yein01uWWi5O3+hO8TcZoygmaf9UDauByLsPu8)
#  authorizer-user: ENC(GGpShf5jjKUvVZk82lCTSFidrZk9JekQ1nrr0Wd5Ur33iXlpWWSFlcNr8dhzcHWA)
#  user:
#    name: ENC(/eZnt0AkGoU7KkzYx5zYXP/jll8P96o1fR3+wRrMWD6HyS1vRX/xeIGPzDbOnsmy)
#    password: ENC(Nmw+5R2uZPnHX6rLgS+ZI+7/kkVBSyXQcAnXYLAo85Zk5cR5eKOS4loEljYbOKrl)
#jasypt:
#  encryptor:
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator




#spring:
#  main:
#    lazy-initialization: true
#    allow-bean-definition-overriding: true
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true
#  application:
#    name: 'multiple account API'
#    properties:
#      hibernate:
#        dialect:
#          - 'org.hibernate.dialect.Oracle12cDialect'
#          - 'org.hibernate.dialect.SQLServer2012Dialect'
#    show-sql: true
#  datasource:
#  jpa:
#    generate-ddl: true
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    #    username: sa
#    #    password: P@ss@12345
#    #    jdbcUrl: jdbc:sqlserver://10.1.12.110:1433;encrypt=false;instanceName=EBSQLSRV;databaseName=mulitAcount
#    username: mtesfa
#    password: P@ss2345
#    jdbcUrl: jdbc:sqlserver://localhost:1433;instanceName=EBSQLSRV;databaseName=arifpay;encrypt=false
#  #    username: root
#  #    password:
#  #    url: jdbc:mysql://localhost:3306/EWBFS
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: 'http://10.1.22.72:8081/auth/realms/enat'
##          issuer-uri: 'http://10.1.12.70:8081/auth/realms/enat'
##          issuer-uri: 'http://localhost:8282/realms/maze'
#db2:
#  datasource:
#    driverClassName: oracle.jdbc.OracleDriver
#    jdbcUrl: jdbc:oracle:thin:@//10.1.10.218:1521/EBPROD1
#    password: password
#    username: ebfcread
#    hibernate:
#      ddl-uto: none
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://10.1.22.72:8761/eureka}
#  #      defaultZone: ${EUREKA_URI:http://10.1.12.70:8761/eureka}
#  #      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  #      defaultZone: ${EUREKA_URI:http://localhost:9090/discovery-service-0.0.1-SNAPSHOT/eureka}
#  instance:
#    preferIpAddress: true
#client:
#  hr:
#    baseUrl: 'http://10.1.12.70:8083/hr'
##    baseUrl: 'http://localhost:8083'
##    baseUrl: 'http://localhost:9090/hr-0.0.1-SNAPSHOT'
#services:
#  hr: 'http://10.1.22.72:8083/hr'
##  hr: 'http://localhost:8083'
##  hr: 'http://10.1.12.70:8083/hr'
##  hr: 'http://localhost:9090/hr-0.0.1-SNAPSHOT'
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#application:
#  allowedOrigin:
#    - 'http://10.1.22.72:5010'
#    - 'http://10.1.12.70:5010'
#    - 'http://localhost:4200'


#  select SWTM_CARD_DETAILS.ATM_CARD_NO,fcc_acc_no , sttm_cust_personal.mobile_number as mobile ,
#  sttm_cust_personal.P_address1 as adress1 ,
#  sttm_cust_personal.P_address2 as adress2,
#  sttm_cust_personal.P_address3 as adress3,
#  STTM_CUSTOMER.customer_name1 AS CUSTOMERNAME,STTM_CUSTOMER.CUSTOMER_NO AS CUSTNUMBER from SWTM_CARD_DETAILS
#  JOIN sttm_cust_account
#  ON sttm_cust_account.cust_ac_no=  SWTM_CARD_DETAILS.FCC_ACC_NO
#  JOIN STTM_CUSTOMER
#  ON STTM_CUSTOMER.CUSTOMER_NO=sttm_cust_account.cust_no
#  JOIN sttm_cust_personal
#  ON sttm_cust_personal.CUSTOMER_NO=  sttm_cust_account.cust_no
#  where  SWTM_CARD_DETAILS.fcc_acc_no  = '0011102147213002';